<pre>
- Choose from ships
- Purpose: Trip, Day Sail, Equipment Test
- Entry Date
- Departure time
- Estimated Arrival time
- Actual Arrival Time
- Mileage
- Skipper
- Crew
- Guests
- Weather forecast
- Weather observed
- Food Consumed
- People met
- Average Motor RPMs
- Fuel intake
- Fuel used
- Water intake
- Water used
- Route (textarea)
</pre>